export const BLACK_MANTA_QUOTES = [
  "Atlantis will be ashes in my wake.",
  "Even the Trench fear me.",
  "Revenge is all that matters.",
  "Meet the Devil.",
  "You will sink like a stone.",
  "Die without dignity.",
  "I smell blood in the water.",
  "Dead kings are my specialty.",
  "I will pay any price for vengeance.",
  "I'll gut you like a fish.",
  "Everybody dies.",
  "What does it feel like to die?",
  "You'll be the first to die today.",
  "Pressure crushing you yet?",
  "This won't be catch and release.",
  "I'll fillet you like a fish.",
  "Let's see if your corpse floats.",
  "Choke on a harpoon!",
  "I'll bleed you out slowly.",
  "I'm the predator. You're the prey.",
  "I don't leave witnesses.",
  "I'm deadly in the water and out.",
  "A fool like you can't stop me.",
  "I'd rather die here.",
  "First rule: don't leave loose ends.",
  "Killing you won't take long.",
  "My rays burn.",
  "I brought a hook to hang you from.",
  "A clean PR is sharper than any blade.",
  "The code should fear you slightly.",
  "Multiple fronts. Maximum damage. Classic strategy.",
  "More money, more action, more lines shipped. The only acceptable direction.",
  "Make progress loud enough to bother Atlantis.",
  "Aquaman manages one kingdom. You manage more tasks than that before lunch.",
  "I came for Aquaman. I stayed because this board is a weapon.",
  "More. Always more.",
] as const;

export function randomBlackMantaQuote(): string {
  return BLACK_MANTA_QUOTES[Math.floor(Math.random() * BLACK_MANTA_QUOTES.length)] ?? BLACK_MANTA_QUOTES[0];
}
